apiVersion: node.eks.aws/v1alpha1
kind: NodeConfig
spec:
    cluster:
        apiServerEndpoint: https://0471B0DE86DB9EBEA17B7F5C9DD83C61.yl4.us-east-2.eks.amazonaws.com
        certificateAuthority: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTVM2Z2kyeUxFS1l3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBNE1ESXhPREUyTWpaYUZ3MHpOVEEzTXpFeE9ESXhNalphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUM4dkZ0NWtvL2NNa2NtalI3enZXdXhFWmdlQ1hNZm0rZC9CV3BYbHpzcFQrSXhGMUlGbmt1R2F5Y20KUFRXVkdtZDNiOHBza29xc3Y3UXZnb3lMeW1GMVpCRHBGbVU2eG00Y1JxeHFGOVQ0b3pSUzlBekh5UVBxVEZxLwpzSWx2Skd2QWcrK0trMDlncFdaOEFscGY0SlFkMEtIV2cxc2ZQMnBIa1RadjhTcXRpaTR1MGpaZ2x4azJnYWdGCnFxTUdyZzZQaXBpYjdBODN0RUdHV0V1aHBVbHFtYzMrbERiZDFnbjFzSHZ4a1YvaGw1N0p2UnpRaC95dHZOYXgKWUdCR1BwRWd4V2lpWm9NUElHUm56Q29VOWo1WXlTdThib3IxemV5Y1VJKy9TSW93V1dRRmJxajRVVVZPSk1FTQp4S0RqRlVDeHhCTWtGZk9nRWhKRm9OWTJGR0RIQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRRGcxZVZHcTVnb3hEdXZjUklUSUVqUlhPZENEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQnBVMlFpZDcxWApoOWpId3lNLzZUTkEvVnE5VXF6R2gzcmd3a3dGeC8wbEJHWm1HNVI0QytHZzdyMVEveFhKYnVML0VYbWlEaDZSCklPb3lPUEVsQ2N3WGM1Zmxzam1PRWwzb3Z4TExiLzdQdjkyUlYxem41KzBpNnp3QzZHeXNtdmc3eXIrR3JURzQKS3lQSm1mTHNzeUlNeUhOcEpKT2N5K3diWjNTYkNVNzFYY0lvMVIxYWhROHloQy9YME5YeHl4L0V6RUdDWW5BdwpZRnNUajhrcEZRUmhIbVFVS0J6bldRUWRTNUluUCsycTY4YXFBVTEvQXFoeGhLdkxQUFBWZ0VDRFovUDJBMHpWCm1XUFNwQzI0bTdPRWNZRnlwYitiTjRUR1VBZWNFVjVKTS8yakFjR1VHclJhWjZBT1JuTml2b2h0a3NpYnl5MDIKVDBFS3k3K0xKUnVNCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        cidr: 10.100.0.0/16
        name: peculiar-funk-rainbow
    kubelet:
        config:
            kubeReserved:
                cpu: 100m
                ephemeral-storage: 1Gi
                memory: 200Mi
            systemReserved:
                cpu: 100m
                memory: 200Mi
