apiVersion: node.eks.aws/v1alpha1
kind: NodeConfig
spec:
    cluster:
        apiServerEndpoint: endpoint
        certificateAuthority: dfhhdb
        cidr: 10.100.0.0/16
        name: name
    kubelet:
        config:
            kubeReserved:
                cpu: 100m
                ephemeral-storage: 1Gi
                memory: 200Mi
            systemReserved:
                cpu: 100m
                memory: 200Mi
